[package]
name = "nes_emulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["debug"]
debug = []

[dependencies]
anyhow = "1.0.71"
once_cell = "1.18.0"
paste = "1.0.14"
nes_debug = {path = "../nes_debugger_tui"}

# this area is for tests only and is never included in the binary
[dev-dependencies]
rstest = "0.18.2"
