[package]
name = "start"
version = "0.1.0"
edition = "2021"

[features]
# default = ["debug"] /// add this so that the 
default = ["debug"]
debug = ["iced"]
iced = ["dep:iced"]


[dependencies]
anyhow = "1.0.71"
features = "0.10.0"
geometry = "0.2.0"
iced = { version = "0.13.1", features = [
  "debug",
  "advanced",
  "lazy",
], optional = true }
iced_aw = "0.11.0"
# iced_table = "0.12.0"
once_cell = "1.18.0"
# coffee = { version = "0.4", features = ["opengl"] }
log = "0.4.22"
pretty_env_logger = "0.5.0"
components = { path = "../components"}
debug = { path = "../debug"}


[dev-dependencies]
tracing = { version = "0.1.40" }
rstest = "*"

